'use strict';

// set empty arrays for gameBoxes and userBoxes
var gameBoxes = [];
var userBoxes = [];

var fadeInOut = function() {
	$(this).animate({
		opacity: '0.5',
	}, 100);
	$(this).animate({
		opacity: '1',
	}, 500);
};

$('.top.left').click(fadeInOut);
$('.top.right').click(fadeInOut);
$('.bottom.right').click(fadeInOut);
$('.bottom.left').click(fadeInOut);

var counter = 0;
var max = 4;
var clickCounter = 0;
var interval = 1000;

var dataNumber = function() {
	userBoxes.push(parseInt($(this).data('number')));
};

// once gameBoxes length equals userBoxes length, checks the arrays
var checkArrays = function() {	
	if (userBoxes === gameBoxes) {
		alert('Woohoo! Way to go!');
	} else {
		alert('Nope, sorry!');
		console.log(userBoxes);
		console.log(gameBoxes);
	}
};

// initiate game interval
var theGame = function() {

	var gameSequence = setInterval(function() {

		$('h1').html('Watch closely!');

	    if (counter <= max) {
			// random takes the value generated by getRandomInt
			// boxes targets children in game div (presented as an array)
			// randomBox selects a random box
			// lightBox lights up the random box that was selected + pushes its index to gameBoxes array
			// then, counter++ resets the counter until counter > max
			var getRandomInt = function() {
				return Math.floor(Math.random() * 4);
			};

			var random = getRandomInt();
			var boxes = $('#game').children();

			var randomBox = $(boxes[random]);

			var lightBox = function() {
				$(randomBox).animate({
					opacity: 0.5,
				}, 100);
				$(randomBox).animate({
					opacity: 1,
				}, 500);
				gameBoxes.push(random);
				console.log(random);
			};

	        lightBox();
	        counter++;
	        console.log('counter: ' + counter); 
	    
	    } else {
	    	clearInterval(gameSequence);
			$('h1').html('Your turn!');
			console.log(gameBoxes);

			// yourTurn activates box-click push to array
			var yourTurn = function() {
				var activeButton = setInterval(function() {
					$('#game').children().addClass('active-btn');
					
					while (clickCounter < max) {
						$('#game').on('.active-btn', dataNumber);
						
						clickCounter++;
					} 	
				}, 2000);
			};

			yourTurn();
			checkArrays();
	 	}
	
	}, interval);
};
	
$('#start-btn').click(theGame);




